# HW

In [ ]:
import numpy as np
import pandas as pd

##### Загрузите датасет titanic.csv

In [2]:
df_titanic = pd.read_csv('titanic.csv')

In [3]:
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df_titanic.shape

(891, 12)

In [5]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


> Обратите внимание на разное количество значений переменных
Если это так - то у вас пропуски в данных. Такое бывает. 
Например в этом датасете не получилось выяснить всех подробностей у некоторых людей в виду утери данных, невозможности узнать или восстановить их

In [6]:
df_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

> Давайте возьмем для начала только несколько признаков, позже - вы увеличите их количество и сделаете соответствующую обработку.

In [7]:
columns = ['Sex', 'Age', 'Pclass', 'Survived']

In [8]:
simple_train = df_titanic[columns].loc[:500]
simple_test = df_titanic[columns].loc[500:]

> мы пока не умеем на уровне алгоритма работать с пропущенными значениями. 
Представьте вам дают 5-мерный вектор у которого заполнены только три компоненты и другой такой же вектор но у него заполнены лишь две  компоненты.  Как померить их сходство????

distance_between( [1,0,1, NaN, NaN], [NaN, 1, 1, NaN, NaN] )


> один из вариантов - заполнить какими то значениями - например если это возраст - то заполнить средним по датасету или нулем.

>> на будущее - в sklearn есть такой модуль - http://scikit-learn.org/stable/modules/impute.html но сейчас можете заполнить пропуски средствами pandas - метод fillna()

##### Заполните пропущенные значения чем нибудь

In [9]:
simple_train = simple_train.fillna(simple_train.mean())
simple_test = simple_test.fillna(simple_test.mean())
#simple_train = simple_train.fillna(0)
#simple_test = simple_test.fillna(0)
# можно inplace делать такое, а можно переприсваивать.

> мы чемпионы. Но мы понимаем, что алгоритм у нас метрический - он не понимает как померить близость векторов в которых содержатся строки

distance( [1,1,0,'мужик'], [1, 0, 1, 'принцесска'] )

> поэтому давайте заведем признак is_man который будет принимать значение 0 или 1.

##### Заведите бинарный признак отвечающий за пол. Строковый удалите

хинт - есть метод apply()

In [10]:
simple_train.Sex = simple_train.Sex.apply(lambda x: 1 if x == "male" else 0)
simple_test.Sex = simple_test.Sex.apply(lambda x: 1 if x == "male" else 0)

##### Сформируйте трейн и тест выборку, где в X лежат признаки 'Sex', 'Age', 'Pclass', а в у - Survived

Результат - numpy array

hint - у pandas есть метод drop() и атрибут values; Пощупайте их

In [11]:
X_train = np.array(simple_train[['Sex', 'Age', 'Pclass']])
X_test = np.array(simple_test[['Sex', 'Age', 'Pclass']])
y_train = np.array(simple_train.Survived)
y_test = np.array(simple_test.Survived)

In [12]:
assert isinstance(X_train, np.ndarray)
assert isinstance(X_test, np.ndarray)
assert isinstance(y_train, np.ndarray)
assert isinstance(y_test, np.ndarray)

In [13]:
assert X_train.shape[0] == y_train.shape[0]
assert X_test.shape[0] == y_test.shape[0]

In [14]:
assert not np.any(np.isnan(X_train)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'
assert not np.any(np.isnan(X_test)), 'у вас в данных есть пропущенные значения. Заполните их или удалите'

##### Реализуйте KNN. Сами, как делали это на лекции. 

Можете улучшить его.
(например использовать kd-tree для быстрого поиска ближайших соседей, 
 или обходить соседей и класть расстояния в мин-кучу - тогда вы быстрее будете набирать их, без сортировки.)

In [15]:
class KNN:
    """
    simple KNN classifier with O(n) complexity for memory,
    and O(n log n) complexity - for nn search.
    """
    
    def __init__(self, n):
        self.n = n
        
    def fit(self, X, y):
        self.X = X
        self.y = y
    
    def predict(self, X):
        y_hat = []
        assert len(X.shape) == 2
        for line in X:
            d = 0;
            for i in range(len(line)):
                d += (self.X[:,i] - line[i])**2
            d = np.sqrt(d)
            idx = np.argsort(d)[: self.n]
            counts = np.bincount(self.y[idx])
            prediction = np.argmax(counts)
            y_hat.append(prediction)
        return np.array(y_hat)

In [16]:
knn = KNN(5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

##### посчитайте руками (не используя sklearn) качество вашего предсказания

In [17]:
acc = np.mean(y_pred == y_test)
print('доля правильных ответов:', acc)

доля правильных ответов: 0.7851662404092071


In [18]:
np.unique(y_pred)

array([0, 1], dtype=int64)

> Мы получили бейслайн решение. Оно должно давать скорр в районе 0.76

____

In [19]:
### можете проверить себя

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7851662404092071


In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

np.unique(y_pred)

print(accuracy_score(y_test, y_pred))

0.7774936061381074


##### TODO продолжение домашки

### Проведем повторную подготовку данных, сразу с увеличением колличества признаков

In [21]:
new_data = df_titanic
new_data.head(1)

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [22]:
new_data = new_data.drop(["Name", "Ticket", "PassengerId"],axis=1)

In [23]:
new_data.head(1)

Survived  Pclass   Sex   Age  SibSp  Parch  Fare Cabin Embarked
0         0       3  male  22.0      1      0  7.25   NaN        S

In [24]:
n = new_data.Embarked.unique()
for i in range(len(n)):
    new_data.Embarked = new_data.Embarked.apply(lambda x: i if x == n[i] else x)

In [25]:
new_data.Embarked.unique()

array([ 0.,  1.,  2., nan])

In [26]:
n = new_data.Cabin.unique()
for i in range(len(n)):
    new_data.Cabin = new_data.Cabin.apply(lambda x: i if x == n[i] else x)

In [27]:
new_data.Cabin.unique()

array([ nan,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147.])

In [28]:
n = new_data.Sex.unique()
for i in range(len(n)):
    new_data.Sex = new_data.Sex.apply(lambda x: i if x == n[i] else x)

In [29]:
new_data.Sex.unique()

array([0, 1], dtype=int64)

#### теперь избавимся от нанов

In [30]:
new_data = new_data.fillna(new_data.mean())

In [31]:
new_data.head(5)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare      Cabin  Embarked
0         0       3    0  22.0      1      0   7.2500  67.818627       0.0
1         1       1    1  38.0      1      0  71.2833   1.000000       1.0
2         1       3    1  26.0      0      0   7.9250  67.818627       0.0
3         1       1    1  35.0      1      0  53.1000   2.000000       0.0
4         0       3    0  35.0      0      0   8.0500  67.818627       0.0

#### стандартизируем и отшкалируем данные

In [32]:
Full_X = new_data.drop("Survived", axis=1)
Full_X = (Full_X - Full_X.mean(axis=0)) / Full_X.std(axis=0)
Full_Y = new_data.Survived

In [33]:
Full_X = (Full_X - Full_X.min(axis=0)) / (Full_X.max(axis=0) - Full_X.min(axis=0))

In [34]:
X_train = np.array(Full_X.loc[:300])
X_test = np.array(Full_X.loc[300:])
y_train = np.array(Full_Y.loc[:300])
y_test = np.array(Full_Y.loc[300:])

In [35]:
knn = KNN(5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [36]:
acc = np.mean(y_pred == y_test)
print('доля правильных ответов:', acc)

доля правильных ответов: 0.7918781725888325


In [37]:
np.unique(y_pred)

array([0, 1], dtype=int64)

In [38]:
### можете проверить себя

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7918781725888325


In [39]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

np.unique(y_pred)

print(accuracy_score(y_test, y_pred))

0.7918781725888325
